version: '3'
services:
  #buld nginx container
  nginx:
    container_name: nginx
    build: ./nginx
    depends_on:
      - website1
      - website2
    ports:
      - 80:80
    volumes:
      - /home/ubuntu/data/:/data  
    networks:
      vpcbr:
           ipv4_address: "10.5.0.5"

#build node container
  website1:
    container_name: website1
    build: ./node
    environment:
      - PORT=8080
    networks:
      vpcbr:
           ipv4_address: "10.5.0.11"
  website2:
    container_name: website2
    build: ./node
    environment:
      - PORT=8081
    networks:
      vpcbr:
           ipv4_address: "10.5.0.12"

#build docker network
networks:
  vpcbr:
      driver: bridge
      ipam:
        config:
          - subnet: 10.5.0.0/16
